import type { Employee } from "@/lib/types/employee.types"

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "emp-001",
    email: "emily.rodriguez@goalflow.com",
    name: "Emily Rodriguez",
    title: "Senior Software Engineer",
    department: "Engineering",
    departmentId: "dept-eng",
    managerId: "mgr-001",
    managerName: "Michael Chen",
    role: "employee",
    status: "active",
    startDate: "2022-03-15",
    avatar: "/software-engineer-workspace.png",
    location: "San Francisco, CA",
    skills: ["React", "Node.js", "TypeScript", "AWS"],
    performanceScore: 4.5,
    goalCompletionRate: 85,
    lastReviewDate: "2024-03-15",
    nextReviewDate: "2025-03-25",
  },
  {
    id: "emp-002",
    email: "john.smith@goalflow.com",
    name: "John Smith",
    title: "Product Designer",
    department: "Design",
    departmentId: "dept-design",
    managerId: "mgr-002",
    managerName: "Sarah Kim",
    role: "employee",
    status: "active",
    startDate: "2023-01-10",
    location: "New York, NY",
    skills: ["Figma", "UI/UX", "Prototyping"],
    performanceScore: 4.2,
    goalCompletionRate: 78,
  },
  {
    id: "emp-003",
    email: "maria.garcia@goalflow.com",
    name: "Maria Garcia",
    title: "Marketing Manager",
    department: "Marketing",
    departmentId: "dept-marketing",
    managerId: "mgr-003",
    managerName: "Tom Wilson",
    role: "employee",
    status: "active",
    startDate: "2021-06-01",
    location: "Austin, TX",
    skills: ["SEO", "Content Marketing", "Analytics"],
    performanceScore: 4.7,
    goalCompletionRate: 92,
  },
]
