import type { Goal } from "@/lib/types/goal.types"

export const MOCK_GOALS: Goal[] = [
  {
    id: "goal-001",
    title: "Increase Platform Performance by 30%",
    description: "Optimize database queries and implement caching to reduce response times",
    type: "company",
    status: "on_track",
    priority: "high",
    progress: 65,
    ownerId: "exec-001",
    ownerName: "David Williams",
    startDate: "2025-01-01",
    dueDate: "2025-12-31",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-03-15T10:00:00Z",
    metrics: [
      { id: "m1", name: "Page Load Time", target: 1.5, current: 2.1, unit: "seconds" },
      { id: "m2", name: "API Response Time", target: 200, current: 350, unit: "ms" },
    ],
    alignedGoals: ["goal-002", "goal-003"],
    tags: ["performance", "infrastructure"],
  },
  {
    id: "goal-002",
    title: "Launch Mobile App",
    description: "Design and develop native mobile applications for iOS and Android",
    type: "department",
    status: "on_track",
    priority: "critical",
    progress: 45,
    ownerId: "mgr-001",
    ownerName: "Michael Chen",
    departmentId: "dept-eng",
    departmentName: "Engineering",
    parentGoalId: "goal-001",
    startDate: "2025-02-01",
    dueDate: "2025-08-31",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-03-14T15:30:00Z",
    metrics: [
      { id: "m3", name: "Feature Completion", target: 100, current: 45, unit: "%" },
      { id: "m4", name: "Test Coverage", target: 80, current: 65, unit: "%" },
    ],
    tags: ["mobile", "development"],
  },
  {
    id: "goal-003",
    title: "Implement Authentication System",
    description: "Build secure OAuth 2.0 authentication with multi-factor authentication support",
    type: "individual",
    status: "on_track",
    priority: "high",
    progress: 75,
    ownerId: "emp-001",
    ownerName: "Emily Rodriguez",
    departmentId: "dept-eng",
    departmentName: "Engineering",
    parentGoalId: "goal-002",
    startDate: "2025-02-15",
    dueDate: "2025-04-30",
    createdAt: "2025-02-15T00:00:00Z",
    updatedAt: "2025-03-16T09:00:00Z",
    metrics: [{ id: "m5", name: "Security Tests Passed", target: 50, current: 42, unit: "tests" }],
    tags: ["security", "authentication"],
  },
  {
    id: "goal-004",
    title: "Improve Customer Satisfaction Score",
    description: "Enhance customer support and reduce response times to improve CSAT to 90%",
    type: "company",
    status: "at_risk",
    priority: "high",
    progress: 35,
    ownerId: "exec-001",
    ownerName: "David Williams",
    startDate: "2025-01-01",
    dueDate: "2025-06-30",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-03-10T14:00:00Z",
    metrics: [
      { id: "m6", name: "CSAT Score", target: 90, current: 78, unit: "%" },
      { id: "m7", name: "Response Time", target: 2, current: 4.5, unit: "hours" },
    ],
    tags: ["customer-success", "support"],
  },
  {
    id: "goal-005",
    title: "Complete Leadership Training",
    description: "Finish advanced leadership certification program",
    type: "individual",
    status: "completed",
    priority: "medium",
    progress: 100,
    ownerId: "mgr-001",
    ownerName: "Michael Chen",
    startDate: "2024-10-01",
    dueDate: "2025-03-31",
    completedDate: "2025-03-20",
    createdAt: "2024-10-01T00:00:00Z",
    updatedAt: "2025-03-20T16:00:00Z",
    metrics: [{ id: "m8", name: "Modules Completed", target: 12, current: 12, unit: "modules" }],
    tags: ["professional-development", "leadership"],
  },
]
