import type {
  DailyActivitySummary,
  FocusSession,
  DailySatisfaction,
  DailyAlert,
  TimelineEvent,
  DailyGoalProgress,
} from "@/lib/types/mobile-activity.types"

const today = new Date().toISOString().split("T")[0]

export const MOCK_FOCUS_SESSIONS: FocusSession[] = [
  {
    id: "fs-001",
    userId: "emp-001",
    startTime: "2025-02-04T08:00:00Z",
    endTime: "2025-02-04T09:30:00Z",
    duration: 90,
    goal: "goal-003",
    status: "completed",
    focusType: "deep_work",
    createdAt: "2025-02-04T08:00:00Z",
  },
  {
    id: "fs-002",
    userId: "emp-001",
    startTime: "2025-02-04T10:00:00Z",
    endTime: "2025-02-04T11:15:00Z",
    duration: 75,
    goal: "goal-002",
    status: "completed",
    focusType: "deep_work",
    createdAt: "2025-02-04T10:00:00Z",
  },
  {
    id: "fs-003",
    userId: "emp-001",
    startTime: "2025-02-04T14:00:00Z",
    endTime: undefined,
    duration: 45,
    goal: "goal-003",
    status: "active",
    focusType: "deep_work",
    createdAt: "2025-02-04T14:00:00Z",
  },
]

export const MOCK_DAILY_SATISFACTION: DailySatisfaction = {
  id: "ds-001",
  userId: "emp-001",
  date: today,
  moodRating: 4,
  moodNote: "Good progress on auth system, feeling productive",
  goalRatings: [
    {
      goalId: "goal-002",
      goalTitle: "Launch Mobile App",
      rating: 3,
      note: "Design phase going well",
    },
    {
      goalId: "goal-003",
      goalTitle: "Implement Authentication System",
      rating: 5,
      note: "Major breakthrough on OAuth flow",
    },
  ],
  overallTrend: "up",
  createdAt: "2025-02-04T17:00:00Z",
  updatedAt: "2025-02-04T17:00:00Z",
}

export const MOCK_DAILY_ALERTS: DailyAlert[] = [
  {
    id: "alert-001",
    userId: "emp-001",
    type: "deadline",
    severity: "critical",
    title: "Goal deadline approaching",
    description:
      "Implement Authentication System due in 2 days (April 30). Currently at 75% progress.",
    relatedGoalId: "goal-003",
    daysUntil: 2,
    actionRequired: true,
    actionUrl: "/goals/my",
    createdAt: "2025-02-04T08:00:00Z",
  },
  {
    id: "alert-002",
    userId: "emp-001",
    type: "focus",
    severity: "warning",
    title: "Behind on focus time",
    description:
      "You've logged 165 minutes today. Your target is 240 minutes. Need 75 more minutes.",
    daysUntil: 0,
    actionRequired: true,
    actionUrl: "/mobile",
    createdAt: "2025-02-04T14:00:00Z",
  },
  {
    id: "alert-003",
    userId: "emp-001",
    type: "progress",
    severity: "warning",
    title: "Goal at risk",
    description:
      "Launch Mobile App is falling behind pace. Only 45% complete with 26 days left.",
    relatedGoalId: "goal-002",
    daysUntil: 26,
    actionRequired: false,
    createdAt: "2025-02-04T09:00:00Z",
  },
  {
    id: "alert-004",
    userId: "emp-001",
    type: "milestone",
    severity: "info",
    title: "Security tests milestone",
    description: "42 of 50 security tests passing. Great progress!",
    relatedGoalId: "goal-003",
    actionRequired: false,
    createdAt: "2025-02-04T12:00:00Z",
  },
]

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "te-001",
    time: "08:00",
    period: "morning",
    title: "Deep focus session",
    type: "focus",
    status: "completed",
    goalId: "goal-003",
  },
  {
    id: "te-002",
    time: "09:45",
    period: "morning",
    title: "Team standup",
    type: "meeting",
    status: "completed",
  },
  {
    id: "te-003",
    time: "10:00",
    period: "morning",
    title: "Authentication implementation",
    type: "focus",
    status: "completed",
    goalId: "goal-003",
  },
  {
    id: "te-004",
    time: "12:00",
    period: "afternoon",
    title: "Lunch break",
    type: "task",
    status: "completed",
  },
  {
    id: "te-005",
    time: "14:00",
    period: "afternoon",
    title: "Focus session - OAuth flow",
    type: "focus",
    status: "in_progress",
    goalId: "goal-003",
  },
  {
    id: "te-006",
    time: "15:30",
    period: "afternoon",
    title: "1:1 with Manager",
    type: "meeting",
    status: "upcoming",
  },
  {
    id: "te-007",
    time: "17:00",
    period: "evening",
    title: "Daily review & reflection",
    type: "task",
    status: "upcoming",
  },
]

export const MOCK_DAILY_GOAL_PROGRESS: DailyGoalProgress[] = [
  {
    goalId: "goal-002",
    goalTitle: "Launch Mobile App",
    progressToday: 2,
    totalProgress: 45,
    focusTimeToday: 75,
    onTrack: false,
    nextMilestone: "Complete iOS design mockups",
    daysRemaining: 26,
  },
  {
    goalId: "goal-003",
    goalTitle: "Implement Authentication System",
    progressToday: 5,
    totalProgress: 75,
    focusTimeToday: 120,
    onTrack: true,
    nextMilestone: "Deploy OAuth endpoints to staging",
    daysRemaining: 2,
  },
  {
    goalId: "goal-004",
    goalTitle: "Improve Customer Satisfaction Score",
    progressToday: 0,
    totalProgress: 35,
    focusTimeToday: 0,
    onTrack: false,
    nextMilestone: "Reduce support response time to 2 hours",
    daysRemaining: 116,
  },
]

export const MOCK_DAILY_ACTIVITY_SUMMARY: DailyActivitySummary = {
  id: "das-001",
  userId: "emp-001",
  date: today,
  totalFocusTime: 165,
  focusSessions: MOCK_FOCUS_SESSIONS,
  targetFocusTime: 240,
  highPriorityTasksCompleted: 2,
  highPriorityTasksTotal: 3,
  satisfaction: MOCK_DAILY_SATISFACTION,
  alerts: MOCK_DAILY_ALERTS,
  timeline: MOCK_TIMELINE_EVENTS,
  activeGoals: MOCK_DAILY_GOAL_PROGRESS,
  createdAt: "2025-02-04T06:00:00Z",
  updatedAt: "2025-02-04T17:00:00Z",
}
