import type {
  Organization,
  Department,
  Team,
  ReportingRelationship,
  OrgNode,
  Location,
  Position,
} from "@/lib/types/organization.types"

// Mock Organization
export const MOCK_ORGANIZATION: Organization = {
  id: "org-001",
  name: "GoalFlow Inc",
  legalName: "GoalFlow Technologies Inc.",
  industry: "technology",
  size: "medium",
  employeeCount: 156,
  structureType: "hierarchical",
  description: "Leading performance management platform helping teams achieve their goals",
  mission: "Empower every team to achieve extraordinary results through transparent goal alignment and continuous feedback.",
  vision: "A world where every employee understands how their work contributes to organizational success.",
  website: "https://goalflow.com",
  logo: "/logo.svg",
  foundedDate: "2020-01-15",
  fiscalYearStart: "1", // January
  timezone: "America/Los_Angeles",
  defaultCurrency: "USD",
  settings: {
    companyName: "GoalFlow Inc",
    industry: "technology",
    size: "medium",
    fiscalYearStart: "1",
    timezone: "America/Los_Angeles",
    reviewCycles: [
      {
        id: "cycle-q",
        name: "Quarterly Review",
        frequency: "quarterly",
        startMonth: 1,
        durationDays: 14,
        includesPeerReview: true,
        includesSelfAssessment: true,
        isActive: true,
      },
      {
        id: "cycle-a",
        name: "Annual Performance Review",
        frequency: "annual",
        startMonth: 12,
        durationDays: 30,
        includesPeerReview: true,
        includesSelfAssessment: true,
        isActive: true,
      },
    ],
    performanceRatingScale: 5,
    goalAlignment: {
      enabled: true,
      cascadeType: "top_down",
      alignmentRequired: true,
      maxGoalLevels: 4,
      weightingEnabled: true,
      autoProgressRollup: true,
    },
    hierarchy: {
      maxDepth: 6,
      allowMatrixReporting: true,
      requireDepartmentForEmployees: true,
      requireTeamForEmployees: false,
    },
    notifications: {
      goalUpdates: true,
      reviewReminders: true,
      recognitionAlerts: true,
    },
  },
  createdAt: "2020-01-15T00:00:00Z",
  updatedAt: "2024-12-01T00:00:00Z",
}

// Mock Departments
export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: "dept-exec",
    organizationId: "org-001",
    name: "Executive Office",
    code: "EXEC",
    description: "Company leadership and strategic direction",
    headId: "exec-001",
    headName: "David Williams",
    headTitle: "Chief Executive Officer",
    employeeCount: 4,
    level: 0,
    order: 0,
    color: "#10b981",
    createdAt: "2020-01-15T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "dept-eng",
    organizationId: "org-001",
    name: "Engineering",
    code: "ENG",
    description: "Product development and technical infrastructure",
    headId: "mgr-001",
    headName: "Michael Chen",
    headTitle: "VP of Engineering",
    parentDepartmentId: "dept-exec",
    employeeCount: 45,
    level: 1,
    order: 0,
    color: "#3b82f6",
    teamIds: ["team-platform", "team-frontend", "team-backend", "team-devops"],
    createdAt: "2020-02-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "dept-product",
    organizationId: "org-001",
    name: "Product",
    code: "PROD",
    description: "Product strategy, design, and user experience",
    headId: "mgr-002",
    headName: "Sarah Kim",
    headTitle: "VP of Product",
    parentDepartmentId: "dept-exec",
    employeeCount: 18,
    level: 1,
    order: 1,
    color: "#8b5cf6",
    teamIds: ["team-design", "team-research"],
    createdAt: "2020-02-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "dept-sales",
    organizationId: "org-001",
    name: "Sales",
    code: "SALES",
    description: "Revenue generation and customer acquisition",
    headId: "mgr-003",
    headName: "Tom Wilson",
    headTitle: "VP of Sales",
    parentDepartmentId: "dept-exec",
    employeeCount: 32,
    level: 1,
    order: 2,
    color: "#f59e0b",
    teamIds: ["team-enterprise", "team-smb", "team-partnerships"],
    createdAt: "2020-02-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "dept-marketing",
    organizationId: "org-001",
    name: "Marketing",
    code: "MKT",
    description: "Brand awareness, demand generation, and communications",
    headId: "mgr-004",
    headName: "Lisa Anderson",
    headTitle: "VP of Marketing",
    parentDepartmentId: "dept-exec",
    employeeCount: 22,
    level: 1,
    order: 3,
    color: "#ec4899",
    teamIds: ["team-growth", "team-content", "team-brand"],
    createdAt: "2020-02-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "dept-hr",
    organizationId: "org-001",
    name: "Human Resources",
    code: "HR",
    description: "People operations, talent acquisition, and culture",
    headId: "hr-001",
    headName: "Sarah Johnson",
    headTitle: "VP of People",
    parentDepartmentId: "dept-exec",
    employeeCount: 12,
    level: 1,
    order: 4,
    color: "#14b8a6",
    teamIds: ["team-recruiting", "team-people-ops"],
    createdAt: "2020-02-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "dept-finance",
    organizationId: "org-001",
    name: "Finance",
    code: "FIN",
    description: "Financial planning, accounting, and operations",
    headId: "mgr-005",
    headName: "Robert Taylor",
    headTitle: "CFO",
    parentDepartmentId: "dept-exec",
    employeeCount: 8,
    level: 1,
    order: 5,
    color: "#64748b",
    createdAt: "2020-02-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "dept-cs",
    organizationId: "org-001",
    name: "Customer Success",
    code: "CS",
    description: "Customer onboarding, support, and retention",
    headId: "mgr-006",
    headName: "Jennifer Lee",
    headTitle: "VP of Customer Success",
    parentDepartmentId: "dept-exec",
    employeeCount: 15,
    level: 1,
    order: 6,
    color: "#06b6d4",
    teamIds: ["team-onboarding", "team-support"],
    createdAt: "2020-02-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
]

// Mock Teams
export const MOCK_TEAMS: Team[] = [
  // Engineering Teams
  {
    id: "team-platform",
    organizationId: "org-001",
    departmentId: "dept-eng",
    name: "Platform Team",
    description: "Core platform infrastructure and APIs",
    leadId: "lead-001",
    leadName: "James Martinez",
    memberIds: ["emp-001", "emp-010", "emp-011", "emp-012"],
    memberCount: 8,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "team-frontend",
    organizationId: "org-001",
    departmentId: "dept-eng",
    name: "Frontend Team",
    description: "Web and mobile user interfaces",
    leadId: "lead-002",
    leadName: "Amy Wong",
    memberIds: ["emp-013", "emp-014", "emp-015"],
    memberCount: 10,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "team-backend",
    organizationId: "org-001",
    departmentId: "dept-eng",
    name: "Backend Team",
    description: "Server-side systems and databases",
    leadId: "lead-003",
    leadName: "Kevin Park",
    memberIds: ["emp-016", "emp-017", "emp-018"],
    memberCount: 12,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "team-devops",
    organizationId: "org-001",
    departmentId: "dept-eng",
    name: "DevOps Team",
    description: "Infrastructure, CI/CD, and reliability",
    leadId: "lead-004",
    leadName: "Chris Davis",
    memberIds: ["emp-019", "emp-020"],
    memberCount: 5,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  // Product Teams
  {
    id: "team-design",
    organizationId: "org-001",
    departmentId: "dept-product",
    name: "Design Team",
    description: "UI/UX design and design systems",
    leadId: "lead-005",
    leadName: "Michelle Tanaka",
    memberIds: ["emp-002", "emp-021", "emp-022"],
    memberCount: 8,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "team-research",
    organizationId: "org-001",
    departmentId: "dept-product",
    name: "Research Team",
    description: "User research and product analytics",
    leadId: "lead-006",
    leadName: "Daniel Brown",
    memberIds: ["emp-023", "emp-024"],
    memberCount: 4,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  // Sales Teams
  {
    id: "team-enterprise",
    organizationId: "org-001",
    departmentId: "dept-sales",
    name: "Enterprise Sales",
    description: "Large account acquisition and management",
    leadId: "lead-007",
    leadName: "Mark Johnson",
    memberIds: ["emp-025", "emp-026", "emp-027"],
    memberCount: 12,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "team-smb",
    organizationId: "org-001",
    departmentId: "dept-sales",
    name: "SMB Sales",
    description: "Small and medium business sales",
    leadId: "lead-008",
    leadName: "Rachel Green",
    memberIds: ["emp-028", "emp-029", "emp-030"],
    memberCount: 15,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  // Marketing Teams
  {
    id: "team-growth",
    organizationId: "org-001",
    departmentId: "dept-marketing",
    name: "Growth Team",
    description: "Demand generation and performance marketing",
    leadId: "lead-009",
    leadName: "Alex Rivera",
    memberIds: ["emp-003", "emp-031", "emp-032"],
    memberCount: 8,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "team-content",
    organizationId: "org-001",
    departmentId: "dept-marketing",
    name: "Content Team",
    description: "Content strategy and creation",
    leadId: "lead-010",
    leadName: "Emma White",
    memberIds: ["emp-033", "emp-034"],
    memberCount: 6,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  // HR Teams
  {
    id: "team-recruiting",
    organizationId: "org-001",
    departmentId: "dept-hr",
    name: "Recruiting Team",
    description: "Talent acquisition and employer branding",
    leadId: "lead-011",
    leadName: "Nicole Adams",
    memberIds: ["emp-035", "emp-036"],
    memberCount: 5,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "team-people-ops",
    organizationId: "org-001",
    departmentId: "dept-hr",
    name: "People Operations",
    description: "HR operations and employee experience",
    leadId: "lead-012",
    leadName: "Patricia Moore",
    memberIds: ["emp-037", "emp-038"],
    memberCount: 4,
    type: "functional",
    status: "active",
    createdAt: "2020-03-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  // Cross-functional project team example
  {
    id: "team-q1-launch",
    organizationId: "org-001",
    departmentId: "dept-product",
    name: "Q1 Product Launch",
    description: "Cross-functional team for Q1 major release",
    leadId: "mgr-002",
    leadName: "Sarah Kim",
    memberIds: ["emp-001", "emp-002", "emp-003", "emp-025"],
    memberCount: 12,
    type: "cross_functional",
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
]

// Mock Reporting Relationships
export const MOCK_REPORTING_RELATIONSHIPS: ReportingRelationship[] = [
  // CEO direct reports
  {
    id: "rel-001",
    organizationId: "org-001",
    reporterId: "mgr-001",
    reporterName: "Michael Chen",
    managerId: "exec-001",
    managerName: "David Williams",
    relationshipType: "direct",
    startDate: "2020-02-01",
    isPrimary: true,
  },
  {
    id: "rel-002",
    organizationId: "org-001",
    reporterId: "mgr-002",
    reporterName: "Sarah Kim",
    managerId: "exec-001",
    managerName: "David Williams",
    relationshipType: "direct",
    startDate: "2020-02-01",
    isPrimary: true,
  },
  {
    id: "rel-003",
    organizationId: "org-001",
    reporterId: "mgr-003",
    reporterName: "Tom Wilson",
    managerId: "exec-001",
    managerName: "David Williams",
    relationshipType: "direct",
    startDate: "2020-02-01",
    isPrimary: true,
  },
  {
    id: "rel-004",
    organizationId: "org-001",
    reporterId: "hr-001",
    reporterName: "Sarah Johnson",
    managerId: "exec-001",
    managerName: "David Williams",
    relationshipType: "direct",
    startDate: "2020-02-01",
    isPrimary: true,
  },
  // Engineering hierarchy
  {
    id: "rel-005",
    organizationId: "org-001",
    reporterId: "lead-001",
    reporterName: "James Martinez",
    managerId: "mgr-001",
    managerName: "Michael Chen",
    relationshipType: "direct",
    startDate: "2020-03-01",
    isPrimary: true,
  },
  {
    id: "rel-006",
    organizationId: "org-001",
    reporterId: "emp-001",
    reporterName: "Emily Rodriguez",
    managerId: "lead-001",
    managerName: "James Martinez",
    relationshipType: "direct",
    startDate: "2022-03-15",
    isPrimary: true,
  },
  // Matrix reporting example
  {
    id: "rel-matrix-001",
    organizationId: "org-001",
    reporterId: "emp-001",
    reporterName: "Emily Rodriguez",
    managerId: "mgr-002",
    managerName: "Sarah Kim",
    relationshipType: "dotted",
    startDate: "2024-01-01",
    isPrimary: false,
    notes: "Cross-functional collaboration for Q1 Launch project",
  },
]

// Mock Org Chart
export const MOCK_ORG_CHART: OrgNode = {
  id: "exec-001",
  name: "David Williams",
  title: "Chief Executive Officer",
  email: "ceo@goalflow.com",
  avatar: "/diverse-ceo-group.png",
  department: "Executive Office",
  departmentId: "dept-exec",
  level: 0,
  directReports: 6,
  totalReports: 155,
  goals: {
    total: 5,
    completed: 2,
    atRisk: 0,
  },
  children: [
    {
      id: "mgr-001",
      name: "Michael Chen",
      title: "VP of Engineering",
      email: "manager@goalflow.com",
      avatar: "/engineering-manager.png",
      department: "Engineering",
      departmentId: "dept-eng",
      level: 1,
      directReports: 4,
      totalReports: 44,
      goals: {
        total: 8,
        completed: 3,
        atRisk: 1,
      },
      children: [
        {
          id: "lead-001",
          name: "James Martinez",
          title: "Tech Lead - Platform",
          email: "teamlead@goalflow.com",
          avatar: "/tech-lead.png",
          department: "Engineering",
          departmentId: "dept-eng",
          teamId: "team-platform",
          teamName: "Platform Team",
          managerId: "mgr-001",
          level: 2,
          directReports: 7,
          totalReports: 7,
          goals: {
            total: 6,
            completed: 2,
            atRisk: 1,
          },
          children: [
            {
              id: "emp-001",
              name: "Emily Rodriguez",
              title: "Senior Software Engineer",
              email: "employee@goalflow.com",
              avatar: "/software-engineer-workspace.png",
              department: "Engineering",
              departmentId: "dept-eng",
              teamId: "team-platform",
              teamName: "Platform Team",
              managerId: "lead-001",
              level: 3,
              directReports: 0,
              totalReports: 0,
              goals: {
                total: 4,
                completed: 2,
                atRisk: 0,
              },
            },
          ],
        },
        {
          id: "lead-002",
          name: "Amy Wong",
          title: "Tech Lead - Frontend",
          department: "Engineering",
          departmentId: "dept-eng",
          teamId: "team-frontend",
          teamName: "Frontend Team",
          managerId: "mgr-001",
          level: 2,
          directReports: 9,
          totalReports: 9,
          goals: {
            total: 5,
            completed: 1,
            atRisk: 0,
          },
        },
      ],
    },
    {
      id: "mgr-002",
      name: "Sarah Kim",
      title: "VP of Product",
      department: "Product",
      departmentId: "dept-product",
      level: 1,
      directReports: 2,
      totalReports: 17,
      goals: {
        total: 6,
        completed: 2,
        atRisk: 1,
      },
      children: [
        {
          id: "lead-005",
          name: "Michelle Tanaka",
          title: "Design Lead",
          department: "Product",
          departmentId: "dept-product",
          teamId: "team-design",
          teamName: "Design Team",
          managerId: "mgr-002",
          level: 2,
          directReports: 7,
          totalReports: 7,
          goals: {
            total: 4,
            completed: 1,
            atRisk: 0,
          },
          children: [
            {
              id: "emp-002",
              name: "John Smith",
              title: "Product Designer",
              department: "Product",
              departmentId: "dept-product",
              teamId: "team-design",
              teamName: "Design Team",
              managerId: "lead-005",
              level: 3,
              directReports: 0,
              totalReports: 0,
              goals: {
                total: 3,
                completed: 1,
                atRisk: 0,
              },
            },
          ],
        },
      ],
    },
    {
      id: "mgr-003",
      name: "Tom Wilson",
      title: "VP of Sales",
      department: "Sales",
      departmentId: "dept-sales",
      level: 1,
      directReports: 3,
      totalReports: 31,
      goals: {
        total: 7,
        completed: 4,
        atRisk: 0,
      },
    },
    {
      id: "hr-001",
      name: "Sarah Johnson",
      title: "VP of People",
      email: "hr@goalflow.com",
      avatar: "/hr-director.jpg",
      department: "Human Resources",
      departmentId: "dept-hr",
      level: 1,
      directReports: 2,
      totalReports: 11,
      goals: {
        total: 5,
        completed: 2,
        atRisk: 0,
      },
    },
    {
      id: "mgr-004",
      name: "Lisa Anderson",
      title: "VP of Marketing",
      department: "Marketing",
      departmentId: "dept-marketing",
      level: 1,
      directReports: 3,
      totalReports: 21,
      goals: {
        total: 6,
        completed: 2,
        atRisk: 1,
      },
      children: [
        {
          id: "lead-009",
          name: "Alex Rivera",
          title: "Growth Lead",
          department: "Marketing",
          departmentId: "dept-marketing",
          teamId: "team-growth",
          teamName: "Growth Team",
          managerId: "mgr-004",
          level: 2,
          directReports: 7,
          totalReports: 7,
          goals: {
            total: 4,
            completed: 2,
            atRisk: 0,
          },
          children: [
            {
              id: "emp-003",
              name: "Maria Garcia",
              title: "Marketing Manager",
              department: "Marketing",
              departmentId: "dept-marketing",
              teamId: "team-growth",
              teamName: "Growth Team",
              managerId: "lead-009",
              level: 3,
              directReports: 0,
              totalReports: 0,
              goals: {
                total: 3,
                completed: 2,
                atRisk: 0,
              },
            },
          ],
        },
      ],
    },
    {
      id: "mgr-005",
      name: "Robert Taylor",
      title: "CFO",
      department: "Finance",
      departmentId: "dept-finance",
      level: 1,
      directReports: 2,
      totalReports: 7,
      goals: {
        total: 4,
        completed: 1,
        atRisk: 0,
      },
    },
  ],
}

// Mock Locations
export const MOCK_LOCATIONS: Location[] = [
  {
    id: "loc-001",
    organizationId: "org-001",
    name: "San Francisco HQ",
    type: "headquarters",
    address: "100 Market Street, Suite 500",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94105",
    timezone: "America/Los_Angeles",
    employeeCount: 85,
    isPrimary: true,
    coordinates: {
      lat: 37.7937,
      lng: -122.3965,
    },
  },
  {
    id: "loc-002",
    organizationId: "org-001",
    name: "New York Office",
    type: "branch",
    address: "350 Fifth Avenue, 21st Floor",
    city: "New York",
    state: "NY",
    country: "United States",
    postalCode: "10118",
    timezone: "America/New_York",
    employeeCount: 42,
    isPrimary: false,
    coordinates: {
      lat: 40.7484,
      lng: -73.9857,
    },
  },
  {
    id: "loc-003",
    organizationId: "org-001",
    name: "Austin Office",
    type: "satellite",
    address: "500 W 2nd Street",
    city: "Austin",
    state: "TX",
    country: "United States",
    postalCode: "78701",
    timezone: "America/Chicago",
    employeeCount: 18,
    isPrimary: false,
    coordinates: {
      lat: 30.2672,
      lng: -97.7431,
    },
  },
  {
    id: "loc-004",
    organizationId: "org-001",
    name: "Remote",
    type: "remote",
    address: "Various",
    city: "Various",
    country: "United States",
    timezone: "America/Los_Angeles",
    employeeCount: 11,
    isPrimary: false,
  },
]

// Mock Positions
export const MOCK_POSITIONS: Position[] = [
  {
    id: "pos-001",
    organizationId: "org-001",
    title: "Chief Executive Officer",
    departmentId: "dept-exec",
    level: "executive",
    description: "Overall company leadership and strategy",
    requirements: ["15+ years experience", "Previous CEO/C-suite experience"],
    headcount: 1,
    isVacant: false,
    createdAt: "2020-01-15T00:00:00Z",
  },
  {
    id: "pos-002",
    organizationId: "org-001",
    title: "VP of Engineering",
    departmentId: "dept-eng",
    level: "executive",
    reportsToPositionId: "pos-001",
    description: "Lead all engineering teams and technical strategy",
    requirements: ["10+ years engineering experience", "5+ years management"],
    headcount: 1,
    isVacant: false,
    createdAt: "2020-02-01T00:00:00Z",
  },
  {
    id: "pos-003",
    organizationId: "org-001",
    title: "Tech Lead",
    departmentId: "dept-eng",
    level: "senior",
    reportsToPositionId: "pos-002",
    description: "Lead a technical team and mentor engineers",
    requirements: ["7+ years engineering experience", "Leadership experience"],
    headcount: 4,
    isVacant: false,
    createdAt: "2020-03-01T00:00:00Z",
  },
  {
    id: "pos-004",
    organizationId: "org-001",
    title: "Senior Software Engineer",
    departmentId: "dept-eng",
    level: "senior",
    reportsToPositionId: "pos-003",
    description: "Design and implement complex software systems",
    requirements: ["5+ years engineering experience", "Strong problem-solving skills"],
    headcount: 15,
    isVacant: false,
    createdAt: "2020-03-01T00:00:00Z",
  },
  {
    id: "pos-005",
    organizationId: "org-001",
    title: "Software Engineer",
    departmentId: "dept-eng",
    level: "mid",
    reportsToPositionId: "pos-003",
    description: "Develop and maintain software applications",
    requirements: ["2+ years engineering experience"],
    headcount: 20,
    isVacant: false,
    createdAt: "2020-03-01T00:00:00Z",
  },
]

// Industry options for forms
export const INDUSTRY_OPTIONS = [
  { value: "technology", label: "Technology" },
  { value: "finance", label: "Finance & Banking" },
  { value: "healthcare", label: "Healthcare" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "retail", label: "Retail & E-commerce" },
  { value: "education", label: "Education" },
  { value: "consulting", label: "Consulting" },
  { value: "media", label: "Media & Entertainment" },
  { value: "real_estate", label: "Real Estate" },
  { value: "nonprofit", label: "Nonprofit" },
  { value: "other", label: "Other" },
]

// Company size options
export const COMPANY_SIZE_OPTIONS = [
  { value: "startup", label: "Startup (1-10 employees)" },
  { value: "small", label: "Small (11-50 employees)" },
  { value: "medium", label: "Medium (51-200 employees)" },
  { value: "large", label: "Large (201-1000 employees)" },
  { value: "enterprise", label: "Enterprise (1000+ employees)" },
]

// Organization structure options
export const ORG_STRUCTURE_OPTIONS = [
  { value: "hierarchical", label: "Hierarchical", description: "Traditional top-down structure with clear reporting lines" },
  { value: "flat", label: "Flat", description: "Minimal management layers, emphasizing collaboration" },
  { value: "matrix", label: "Matrix", description: "Employees report to multiple managers (functional and project)" },
  { value: "divisional", label: "Divisional", description: "Organized by product lines, markets, or geography" },
  { value: "functional", label: "Functional", description: "Grouped by specialized function (engineering, marketing, etc.)" },
]

// Timezone options
export const TIMEZONE_OPTIONS = [
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "Europe/London", label: "Greenwich Mean Time (GMT)" },
  { value: "Europe/Paris", label: "Central European Time (CET)" },
  { value: "Asia/Tokyo", label: "Japan Standard Time (JST)" },
  { value: "Asia/Singapore", label: "Singapore Time (SGT)" },
  { value: "Australia/Sydney", label: "Australian Eastern Time (AET)" },
]
